name: enhanced_containers_example
version: 0.0.1
description: This is a basic example on how to use the enhanced_containers package
publish_to: 'none' 

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  enhanced_containers:
    # When depending on this package from a real application you should use:
    #   enhanced_containers: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
    
dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
