name: enhanced_containers_example
version: 0.0.1
description: This is a basic example on how to use the enhanced_containers package
publish_to: 'none' 

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  enhanced_containers:

dependency_overrides:
  enhanced_containers:
    path: ../
  enhanced_containers_foundation:
    path: ../plugins/enhanced_containers_foundation

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
